### ISSUE TITLE
Error in calculating closeness centrality

### ISSUE THREAD

**Issue by sidhantls** [DiegoCao/cs224w_colab#1]
There is a miscalculation when calculating the closeness centrality in this [notebook](https://github.com/DiegoCao/cs224w_colab/blob/master/CS224W_Colab_1_ipynb_chr.ipynb).  

When the result of `nx.algorithms.centrality.closeness_centrality` is being unnormalized in Question 4, it's being divided by `len(component)`. But in fact, it should be divided by `len(component)-1`.  This is because, in `nx.algorithms.centrality.closeness_centrality`, the shortest path is being [normalized](https://github.com/networkx/networkx/blob/f97705493ac84f99aa6ab5aae3129d5dc2578e2c/networkx/algorithms/centrality/closeness.py#L20) by `N-1`, not `N`.  

The answer returned by the function should be ~0.01163 instead of ~0.01128. Correct me if I'm wrong here. Great work on this repo btw

**Comment by DiegoCao** [comment]
I see it, thanks for the correction :rocket: !
